AWSTemplateFormatVersion: "2010-09-09"
Description: This stack deploys the servicediscovery cloudmap

Resources:
  # CloudMapの作成
  PrivateDnsNamespace:
    Type: AWS::ServiceDiscovery::PrivateDnsNamespace
    Properties:
      Vpc:
        Fn::ImportValue: VPCFromServicediscoveryStack
      Name: servicediscovery-test-httpd.internal
      Tags:
        - Key: Name
          Value: servicediscovery-test-PrivateDnsNamespace
  ServiceDiscovery:
    Type: AWS::ServiceDiscovery::Service
    Properties:
      HealthCheckCustomConfig:
        FailureThreshold: 1
      DnsConfig:
        DnsRecords:
          - Type: A
            TTL: 60
        NamespaceId: !GetAtt PrivateDnsNamespace.Id
      Name: "servicediscovery-test-service"

  # CloudMapの作成2
  PrivateDnsNamespace2:
    Type: AWS::ServiceDiscovery::PrivateDnsNamespace
    Properties:
      Vpc:
        Fn::ImportValue: VPCFromServicediscoveryStack
      Name: servicediscovery-test-httpd2.internal
      Tags:
        - Key: Name
          Value: servicediscovery-test-PrivateDnsNamespace2
  ServiceDiscovery2:
    Type: AWS::ServiceDiscovery::Service
    Properties:
      HealthCheckCustomConfig:
        FailureThreshold: 1
      DnsConfig:
        DnsRecords:
          - Type: A
            TTL: 60
        NamespaceId: !GetAtt PrivateDnsNamespace2.Id
      Name: "servicediscovery-test-service2"

  # 検証用のECSサービス作成
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: servicediscovery-test-cluster
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Cpu: 256
      Memory: 512
      Family: servicediscovery-test-httpd-task
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ContainerDefinitions:
        - Name: servicediscovery-test-httpd-container
          Image: httpd:2.4.41-alpine
          PortMappings:
            - ContainerPort: 80
              HostPort: 80
              Protocol: http
          Essential: true
  ECSService:
    Type: "AWS::ECS::Service"
    Properties:
      ServiceName: servicediscovery-test-httpd-container-service
      Cluster: !Ref ECSCluster
      TaskDefinition: !Ref TaskDefinition
      ServiceRegistries:
        - RegistryArn: !GetAtt ServiceDiscovery.Arn
      DesiredCount: 1
      LaunchType: "FARGATE"
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: "DISABLED"
          SecurityGroups:
            - Fn::ImportValue: ContainerSecurityGroupFromServicediscoveryStack
          Subnets:
            - Fn::ImportValue: PrivateOneSubnetFromServicediscoveryStack
            - Fn::ImportValue: PrivateTwoSubnetFromServicediscoveryStack
  ECSService2:
    Type: "AWS::ECS::Service"
    Properties:
      ServiceName: servicediscovery-test-httpd-container-service2
      Cluster: !Ref ECSCluster
      TaskDefinition: !Ref TaskDefinition
      ServiceRegistries:
        - RegistryArn: !GetAtt ServiceDiscovery2.Arn
      DesiredCount: 1
      LaunchType: "FARGATE"
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: "DISABLED"
          SecurityGroups:
            - Fn::ImportValue: ContainerSecurityGroupFromServicediscoveryStack
          Subnets:
            - Fn::ImportValue: PrivateOneSubnetFromServicediscoveryStack
            - Fn::ImportValue: PrivateTwoSubnetFromServicediscoveryStack

Outputs:
  PrivateDnsNamespace:
    Value: !Ref PrivateDnsNamespace
  ServiceDiscovery:
    Value: !Ref ServiceDiscovery
