AWSTemplateFormatVersion: 2010-09-09
Description: This stack deploys the servicediscovery cloud9

# 事前作成リソース
# servicediscovery-network.yml

Parameters:
  NamePrefix:
    Type: String
    Default: "servicediscovery-test"

Resources:
  # Cloud9を作成
  Cloud9:
    Type: AWS::Cloud9::EnvironmentEC2
    Properties:
      AutomaticStopTimeMinutes: 30
      ConnectionType: CONNECT_SSH
      Description: This cloud9 servicediscovery test
      InstanceType: t2.micro
      Name: !Sub ${NamePrefix}-cloud9
      SubnetId:
        Fn::ImportValue: !Sub ${NamePrefix}-Cloud9Subnet

Outputs:
  Cloud9:
    Value: !GetAtt Cloud9.Arn
    Export:
      Name: !Sub ${NamePrefix}-cloud9
