apiVersion: v1
kind: Service
metadata:
  name: my-service-a
  namespace: my-apps
  labels:
    app: test-app-1
spec:
  # type: ClusterIP
  # clusterIP: None
  selector:
    app: test-app-1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-service-a
  namespace: my-apps
  labels:
    app: test-app-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app-1
  template:
    metadata:
      labels:
        app: test-app-1
    spec:
      serviceAccountName: my-service-a
      containers:
        - name: nginx
          image: nginx:1.19.0
          ports:
            - containerPort: 80
